Repository az-digital/az-quickstart-pantheon, pull requests merged in 2024-10, with the labels that each got.

#289 Close #288 Update pantheon_advanced_page_cache from 2.2.0 to 2.3.0 #288
  upstream/composer.json
Labels: bug, dependencies

#291 Closes #290: Allow more open dependabot PRs.
  .github/dependabot.yml
Labels: enhancement, dependencies

#287 Update Pantheon Advanced Page Cache and Config Read Only upstream settings.
  .github/dependabot.yml
  upstream/composer.json
  web/sites/default/settings.upstream.php
Labels: bug, dependencies

#297 Closes #282: Enforce a memory limit for ImageMagick on sites with < 512 MB of memory.
  web/sites/default/settings.upstream.php
Labels: bug, enhancement
